# -*- coding: utf-8 -*-
"""Gorev_1_Samet_Gokboga.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VsUGNmAeuZitrzmomX6JzRs2JOT1XqCl

Soru:1 Dörtgen, üçgen veya  dairenin  Alan hesabı. Kullanıcıdan en boy değerleri alınacak ve alan hesaplanacak.
"""

secim = input("""Hangi şeklin alanını hesaplamak istiyorsunuz:
   (Kare/Dikdörtgen - Üçgen - Daire)            """)
secim = secim.lower().strip()

if secim == "daire":
  yaricap = float(input("Yarıçap Giriniz: "))
  d_alan = (yaricap * yaricap) * 3.14
  print("Girdiğiniz ölçüleerde karenin alanı:", d_alan)

else:
    en = int(input("En Giriniz: "))
    boy = int(input("Boy giriniz: "))
    if secim == "kare" or secim == "dikdörtgen":
      kd_alan = en * boy
      if secim == "kare":
        print("Girdiğiniz ölçüleerde karenin alanı:", kd_alan)
      else:
        print("Girdiğiniz ölçülerde dikdörtgenin alanı alanı:", kd_alan)

    elif secim == "üçgen":
      u_alan = (boy * en)/2
      print("Girdiğiniz ölçülerde üçgenin alanı: ", u_alan)
    else:
      print("Hatalı bir değer girdiniz")

"""SORU:2 Girilen "gün", "saat", "dakika" ve "saniye" değerine göre, toplam saniyeyi hesaplayan bir uygulama yapınız.

"""

gun = int(input("Gün giriniz: "))
saat = int(input("Saat giriniz: "))
dakika = int(input("Dakika giriniz: "))
saniye = int(input("Saniye giriniz: "))

saniye_toplamı = ((gun * 24 * 60 * 60) + (saat * 60 * 60) + (dakika * 60) + saniye)

print("Toplam:",saniye_toplamı, "saniyedir.")

"""3. Vücut Kitle Endeksini hesaplayan uygulamayı yapın (ağırlığın(kg) boyun karesine (m)bölümü)"""

boy = float(input("Boy cm giriniz: "))
kilo = float(input("Kg giriniz: "))

vke = kilo / ((boy/100) * (boy/100))
vke_sonuc = round(vke, 1)
print("Vücut kitle endexsiniz tam olarak: ", vke_sonuc)

"""Restoran. Kullanıcı "pizza", "burger" veya "salata" seçeneklerinden birini seçecek.
Seçtiği menünün fiyatını bir değişkene atayacak.
Bu fiyata %15 vergi oranı uygulayacak, %10 bahşiş ekleyecek ve toplam fiyat yazdırılacak.

"""

y_secim = input("""Ne yemek istersiniz:
Salata: 50
Burger: 100
Pizza: 150
""").lower().strip()

salata = 50
burger = 100
pizza = 150

if y_secim == "salata":
   kdv = (salata * 15)/100
   bahsis = (salata * 10)/100
   print("HKdv ve hizmet bedeli dahil hesabınız: ",salata + kdv + bahsis, "₺")
elif y_secim == "burger":
   kdv = (burger * 15)/100
   bahsis = (burger * 10)/100
   print("Kdv ve hizmet bedeli dahil hesabınız:",burger + kdv + bahsis, "₺")
elif y_secim == "pizza":
   kdv = (pizza * 15)/100
   bahsis = (pizza * 10)/100
   print("Kdv ve hizmet bedeli dahil hesabınız:",pizza + kdv + bahsis, "₺")
else:
  print("O yemeği yapacak şef bulamadık")

"""Soru 5:  feet'i inch, yard, mil e çevirin."""

feet = float(input("Kaç feet çevirmek istiyorsunuz: "))
inch_h = feet * 12
yard_h = feet * 0.3333333
mil_h = feet * 3.040
print(inch_h, yard_h,mil_h)

"""6. Kullanıcı bir kelime girecek, bu kelime "tr" ifadesi içeriyorsa
"kelime tr ifadesi içeriyor" mesajı, içermiyorsa "tr ifadesi içermiyor" mesajı versin.
"""

girdi = input("Kelime giriniz: ")

if "tr" in girdi:
  print("Kelime 'tr' ifadesi içeriyor.")
else:
  print("Kelime 'tr' ifadesi içermiyor.")

"""Kullanıcıdan iki kelime girdisi isteyeceksiniz. ikisinin aynı kelime olup olmadığını kıyaslayacaksınız.
(kullanıcı ister büyük harfle girsin ister küçük. -lower)
"""

kel1 = input("Kelime 1: ").lower()
kel2 = input("Kelime 2: ").lower()

if kel1 == kel2:
  print("2 kelime aynı.")
elif kel1 != kel2:
  print("2 kelime aynı değil")
else:
  print("Yanlış veya hatalı tuşlama yaptınız.")

"""8. Herhangi  bir sayı girsin. Girdiği sayının 100 den büyük, küçük veya eşit olduğu mesajı verilsin.
 (tiplere dikkat)

"""

sayi1 = float(input("Sayı girin: "))

if sayi1 > 100:
  print("Sayınız 100'den büyük.")
elif sayi1 < 100:
  print("Sayınız 100'den küçük.")
elif sayi1 == 100:
  print("Sayınız 100'e eşit.")
else:
  print("HATA!!!")

"""9.Kullanıcı yaşını girecek, 12 yaşa kadar- Çocuk, 13-19 yaş - Ergen, 20-30 yaş Genç yetişkin,
30-64 yaş Yetişkin, 64 yaş üzeri olgun.

"""

yass = int(input("Yaşınızı giriniz: "))


if yass >= 0 and yass <= 12:
  print("Çocuksun tadını çıkar")
elif yass >= 13 and yass <=19:
  print("Ergenlik zordur ama kendine yatırım yapmayı unutma. :)")
elif yass >= 20 and yass <=29:
  print("Genç yetişkin : En ballı yıllar, kimisi işsiz, kimisi evlendi, kimisi ceo :)")
elif yass >= 30 and yass <=64:
  print("YETİŞKİN :D")
elif yass > 64:
  print("Olgun, her şey çok iyi emeklilik vs ama huysuz olma :)")

"""10. Kullanıcı bir kelime girecek, sonu "miş" le mi bitiyor kontrol edilecek. mesaj yazdıracaksınız.

```
# Bu, kod olarak biçimlendirilmiştir
```


"""

kelime = input("Kelime giriniz:")

if kelime[-3:] == "miş":
  print("Sonu 'miş' ile bitiyor")
else:
  print("Sonu 'miş'le bitmiyor. ")

"""11. Hesap makinesi. Kullanıcıdan hangi işlemi yapmak istediği metin olarak alınacak. "bol" "carp" gibi.

"""

islem = ("Hangi işlemi yapmak istiyorsunuz: ").lower().strip()
ilksayi = float(input("Sayı 1: "))
ikincisayi = float(input("Sayı 2: "))

if islem == "topla":
  print(ilksayi, "-",ikincisayi,"=", ilksayi - ikincisayi)
elif islem == "çıkar":
  print(ilksayi, "-",ikincisayi,ilksayi - ikincisayi)
  print(ilksayi, "-",ikincisayi,ilksayi - ikincisayi)

elif islem == "bol":
  print(ilksayi, "-",ikincisayi,ilksayi - ikincisayi)
  print(ilksayi, "-",ikincisayi,ilksayi - ikincisayi)

elif islem == "çarp":
  print(ilksayi, "-",ikincisayi,ilksayi - ikincisayi)
